import type { NextConfig } from "next";

const nextConfig: NextConfig = {
  // Fully static site — deployable to Hostinger static hosting, Vercel, Netlify, etc.
  output: "export",
  trailingSlash: true,
  // Responsive WebP variants are pre-generated by scripts/optimize-images.mjs.
  images: { unoptimized: true },
  reactCompiler: true,
  // A stray lockfile in the home directory would otherwise be picked as the workspace root.
  turbopack: { root: import.meta.dirname },
};

export default nextConfig;
