#!/usr/bin/env node
// Turns the extracted originals in source/images into responsive WebP variants in public/media
// and writes src/data/media.generated.ts (dimensions + blur placeholders) for the app.
//
// Usage: node scripts/optimize-images.mjs   (incremental: existing variants are skipped)

import { readdir, readFile, mkdir, stat, writeFile } from "node:fs/promises";
import { existsSync } from "node:fs";
import path from "node:path";
import os from "node:os";
import sharp from "sharp";

const ROOT = path.resolve(import.meta.dirname, "..");
const SRC = path.join(ROOT, "source/images");
const OUT = path.join(ROOT, "public/media");
const DATA = path.join(ROOT, "src/data/media.generated.ts");
const WIDTHS = [640, 1280, 2048];
const QUALITY = 78;
// Unused media-library uploads that aren't visual duplicates of published photos become the
// "Moments" archive. The list comes from scripts/find-unique-library.mjs (perceptual hashing).
const MOMENTS_FILE = path.join(ROOT, "source/content/moments.json");
const moments = new Set(existsSync(MOMENTS_FILE) ? JSON.parse(await readFile(MOMENTS_FILE, "utf8")) : []);

async function walk(dir, re = /\.(jpe?g|png)$/i) {
  const out = [];
  for (const entry of await readdir(dir, { withFileTypes: true })) {
    const p = path.join(dir, entry.name);
    if (entry.isDirectory()) out.push(...(await walk(p, re)));
    else if (re.test(entry.name)) out.push(p);
  }
  return out;
}

const slugify = (rel) =>
  rel
    .replace(/\.(jpe?g|png)$/i, "")
    .split("/")
    .map((s) => s.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, ""))
    .join("/");

async function processOne(file) {
  const rel = path.relative(SRC, file).split(path.sep).join("/");
  const base = slugify(rel);
  const img = sharp(file, { failOn: "none" }).rotate();
  const meta = await img.metadata();
  const upright = (meta.orientation ?? 1) >= 5;
  const w = upright ? meta.height : meta.width;
  const h = upright ? meta.width : meta.height;
  const widths = WIDTHS.filter((x) => x < w).concat(w < WIDTHS.at(-1) ? [w] : []).slice(0, WIDTHS.length);
  if (!widths.length) widths.push(w);

  for (const width of widths) {
    const dest = path.join(OUT, `${base}-${width}.webp`);
    if (existsSync(dest)) continue;
    await mkdir(path.dirname(dest), { recursive: true });
    await sharp(file, { failOn: "none" })
      .rotate()
      .resize({ width, withoutEnlargement: true })
      .webp({ quality: QUALITY, effort: 4 })
      .toFile(dest);
  }

  const tiny = await sharp(file, { failOn: "none" }).rotate().resize(16).webp({ quality: 40 }).toBuffer();
  return {
    key: rel,
    value: {
      src: `/media/${base}`,
      w,
      h,
      widths,
      blur: `data:image/webp;base64,${tiny.toString("base64")}`,
    },
  };
}

async function pool(items, size, fn) {
  const results = [];
  let i = 0;
  let done = 0;
  await Promise.all(
    Array.from({ length: size }, async () => {
      while (i < items.length) {
        const item = items[i++];
        results.push(await fn(item));
        if (++done % 25 === 0) console.log(`  ${done}/${items.length}`);
      }
    }),
  );
  return results;
}

const files = (await walk(SRC)).filter((f) => {
  const rel = path.relative(SRC, f).split(path.sep).join("/");
  return !rel.startsWith("library-unused/") || moments.has(rel);
});
console.log(`optimizing ${files.length} images…`);
sharp.concurrency(1);
const entries = await pool(files, Math.max(2, os.availableParallelism() - 1), processOne);
entries.sort((a, b) => a.key.localeCompare(b.key));

const media = Object.fromEntries(entries.map((e) => [e.key, e.value]));
const galleries = {};
for (const { key } of entries) {
  const m = key.match(/^photos\/([^/]+)\//);
  if (m) (galleries[m[1]] ??= []).push(key);
  if (key.startsWith("library-unused/")) (galleries.moments ??= []).push(key);
}

await writeFile(
  DATA,
  `// Generated by scripts/optimize-images.mjs — do not edit by hand.
import type { Img } from "@/lib/media";

export const media: Record<string, Img> = ${JSON.stringify(media, null, 2)};

export const galleries: Record<string, string[]> = ${JSON.stringify(galleries, null, 2)};
`,
);

// Social share image from the first hero photo.
const OG_SOURCE = path.join(SRC, "home/DJI_20240901054105_0030_D-Enhanced-NR-1-1-scaled.jpg");
if (existsSync(OG_SOURCE)) {
  await sharp(OG_SOURCE).rotate().resize(1200, 630, { fit: "cover" }).jpeg({ quality: 82, mozjpeg: true }).toFile(path.join(ROOT, "public/og.jpg"));
}

const bytes = (await Promise.all((await walk(OUT, /\.webp$/).catch(() => [])).map((f) => stat(f).then((s) => s.size)))).reduce(
  (a, b) => a + b,
  0,
);
console.log(`done: ${entries.length} images → ${DATA.replace(ROOT + "/", "")} (public/media ≈ ${(bytes / 1e6).toFixed(0)} MB)`);
